### ISSUE TITLE
Does not work in remote development

### ISSUE THREAD

**Issue by OpatrilPeter** [usernamehw/vscode-find-jump#23]
Hello,
extension doesn't specify [extensionKind](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location), tries to run remotely by default and subsequently raises error on executing commands.
```
[2020-12-10 12:33:04.004] [exthost] [error] Error: command 'type' already exists
	at _.registerCommand (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:723:970)
	at Object.registerCommand (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:1044:634)
	at new e.InlineInput (/home/vagrant/.vscode-server-insiders/extensions/usernamehw.find-jump-0.5.1/dist/extension.js:1:3423)
	at activate (/home/vagrant/.vscode-server-insiders/extensions/usernamehw.find-jump-0.5.1/dist/extension.js:1:4624)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:1044:786
	at t.ExtHostTextEditor.edit (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:676:191)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:1044:775
	at _executeContributedCommand (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:725:220)
	at _.$executeContributedCommand (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:725:595)
	at m._doInvokeHandler (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:916:926)
	at m._invokeHandler (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:916:618)
	at m._receiveRequest (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:915:252)
	at m._receiveOneMessage (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:914:6)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:912:136
	at l.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:1119:104
	at l.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:238:1004)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:235:927
	at l.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at p.acceptChunk (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:231:195)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:230:547
	at Socket.t (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23) findJump.activate
[2020-12-10 12:34:48.508] [exthost] [error] TypeError: Cannot read property 'destroy' of undefined
	at e.FindJump.cancel (/home/vagrant/.vscode-server-insiders/extensions/usernamehw.find-jump-0.5.1/dist/extension.js:1:6415)
	at activate (/home/vagrant/.vscode-server-insiders/extensions/usernamehw.find-jump-0.5.1/dist/extension.js:1:4454)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:1044:786
	at t.ExtHostTextEditor.edit (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:676:191)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:1044:775
	at _executeContributedCommand (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:725:220)
	at _.$executeContributedCommand (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:725:595)
	at m._doInvokeHandler (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:916:926)
	at m._invokeHandler (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:916:618)
	at m._receiveRequest (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:915:252)
	at m._receiveOneMessage (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:914:6)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:912:136
	at l.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:1119:104
	at l.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:238:1004)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:235:927
	at l.fire (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at p.acceptChunk (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:231:195)
	at /home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:230:547
	at Socket.t (/home/vagrant/.vscode-server-insiders/bin/5e350b1b79675cecdff224eb00f7bf62ae8789fc/out/vs/server/remoteExtensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23) findJump.activate
```
It seems that simply setting it to run locally does help, verified through override in config as following
```
    "remote.extensionKind": {
        "usernamehw.find-jump": "ui"
    }
```
... so setting extensionKind to `["ui"]` could probably fix it for everyone.

**Comment by usernamehw** [comment]
Thanks.

Why did I even fork this extension, used it exactly **0** times :(
